Repository wecode-bootcamp-korea/10-Weplash-backend, pull requests merged in 2020-08, with the labels that each got.

#1 Add: account app 추가, account/models.py에 User, UserInterest, Interest,…
  account/__init__.py
  account/admin.py
  account/apps.py
  account/migrations/__init__.py
  account/models.py
  account/tests.py
  account/views.py
  config/settings.py
Labels: enhancement

#2 Add : Image model 추가
  account/migrations/0001_initial.py
  account/migrations/0002_like.py
  account/models.py
  account/urls.py
  config/settings.py
  config/urls.py
  photo/__init__.py
  photo/admin.py
  photo/apps.py
  photo/migrations/0001_initial.py
  photo/migrations/__init__.py
  photo/models.py
  photo/tests.py
  photo/urls.py
  photo/views.py
Labels: enhancement

#4 Modify : model 수정
  account/migrations/0003_auto_20200805_1648.py
  account/migrations/0004_auto_20200805_1705.py
  account/models.py
  photo/models.py
Labels: enhancement

#6 Add : mypage profile view 추가
  .gitignore
  account/migrations/0005_auto_20200806_0815.py
  account/migrations/0006_auto_20200806_0958.py
  account/tests.py
  account/urls.py
  account/views.py
  auth.py
  photo/migrations/0002_auto_20200806_0958.py
Labels: 리뷰요청

#7 Add : Photo detail view 추가
  .gitignore
  photo/tests.py
  photo/urls.py
  photo/views.py
Labels: 리뷰요청

#5 Feature/signup
  account/tests.py
  account/urls.py
  account/views.py
  auth.py
Labels: 리뷰요청

#10 Add: kakao social login view
  account/tests.py
  account/urls.py
  account/views.py
Labels: 리뷰요청

#12 Add : SearchBar 기능 구현
  .gitignore
  photo/tests.py
  photo/urls.py
  photo/views.py
Labels: 리뷰요청

#11 Add : User Card 기능 구현
  auth.py
  photo/tests.py
  photo/urls.py
  photo/views.py
Labels: 리뷰요청

#14 Modify : related-collection view 수정
  photo/tests.py
  photo/urls.py
  photo/views.py
Labels: 리뷰요청

#9 파일 업로드 API
  account/migrations/0007_like_status.py
  account/models.py
  account/views.py
  config/__init__.py
  config/celery.py
  config/settings.py
  photo/migrations/0003_photo_status.py
  photo/migrations/0004_remove_photo_status.py
  photo/tasks.py
  photo/tests.py
  photo/urls.py
  photo/views.py
Labels: 리뷰요청

#17 Modify : photo view 수정
  .gitignore
  photo/views.py
Labels: 리뷰요청

#18 Modify : Photo upload view 수정
  account/migrations/0001_initial.py
  account/migrations/0002_auto_20200813_1156.py
  photo/migrations/0001_initial.py
  photo/tasks.py
  photo/tests.py
  photo/urls.py
  photo/views.py
Labels: 리뷰요청

#21 Add : related-photo background color api 추가
  photo/tests.py
  photo/urls.py
  photo/views.py
Labels: 리뷰요청

#16 콜렉션 메인 정보 추가
  photo/urls.py
  photo/views.py
Labels: 수정요청

#22 Add: ModalCollectionView, AddCollectionView, CreateCollectionView
  account/urls.py
  account/views.py
  auth.py
  photo/urls.py
  photo/views.py
Labels: 리뷰요청

#23 Modify : Photo view 수정
  account/views.py
  photo/urls.py
  photo/views.py
Labels: 리뷰요청

#24 검색 후 태그 목록 추가
  photo/urls.py
  photo/views.py
Labels: 리뷰요청
